### PR TITLE
Some improvement in the version of the program and in the about dialog, first try to set some messages to be translated

### PR DESCRIPTION
**Pull request by onekk**

### CODE REVIEW

**Comment by onekk** [comment]
I have left in main.c a string author2 to put maybe our names

**Comment by koppi** [comment]
@onekk I see lots of "Merge branch 'master' in this commit. Please run "git pull --rebase" the next time you pull from upstream, instead of "git pull".

**Comment by onekk** [comment]
@koppi i have done git "pull upstream master" and then "git push" to my repo and then I've done "compare" and make a pull request, when I'm doing wrong?

**Comment by koppi** [comment]
@onekk please pull with the "--rebase" option next time, see why: http://gitready.com/advanced/2009/02/11/pull-with-rebase.html

**Comment by onekk** [comment]
ok thanks, what do you think of the code, it's my first attempt to write something in C.
Regards
Carlo D.

**Comment by koppi** [comment]
In C it is more safe to use snprintf instead of sprintf.

There might be the case, where a user wants to build cammill from a .zip archive that does not contain the .git repo, see as an example:
```bash
$ wget -c https://github.com/cammill/cammill/archive/master.zip
$ unzip master.zip
$ cd cammill-master/
$ make
```
In this case ```"-DGIT_VERSION=\"\""``` and the about dialog looks like:


In this case, I suggest, that you remove the "-" from the version (– just do it as a C programming exercise!).

**Comment by koppi** [comment]
There might also be the case, where a use wants to compile cammill on a system where there is no "git" command installed. I don't know, how make behaves in this case. Can you investigate?

**Comment by onekk** [comment]
Good point of view, i see some scenarios:
1) put a test in the makefile, to the esistence of the .git repo 
2) make it optional in the makefile and put a default value in the C source
3) eliminate the git and retain only the version

I'm thinking of use the 3) as we could track the important change in the version in main.c
As I have put an example version number what do you thinks about it, or better ehat version number we sould use?

Regards

**Comment by koppi** [comment]
I'm totally ignorant to version numbers, but they tend to be useful for cases, where a piece of software gets packaged, i.e. for the inclusion into Debian, there are some rules for version numbers in the Debian packaging system. But I'm totally ignorant to debian packaging, it is useful to have a software packaged for download, but it turned out, that debian and/or rpm packaging is quite painful to get everytihing right.

**Comment by onekk** [comment]
I think there is a convention that number under 1.0 or 1.0.0 are for beta versions, major number say 1.x 2.x for really big changes in the code or in the internals of the program, minor version say 1.1.x 1.2.x are for minor changes in the code for example new functions or major bug fixes and 1.1.1 1.1.2 and so on for bug fixes in the code or minor adjustment in the UI (like the fixing in the translation),
 I think as cammill is quite stable, we can start with 0.9 or maybe leave 0.8 in it and increment the last number when we are fixing the code, here the build version will be useful but i will investigate the Makefile syntax.
What do you think if for now i eliminate the GIT_VERSION think and retain the rest?

**Comment by koppi** [comment]
There is the git "tag" feature which can be used to create version tags, @onekk please investigate howto do this. In github one can setup a downloads section, which can automatically get populated via .travis.yml integration.

**Comment by onekk** [comment]
Maybe tomorrow i will investigate the travis.yml, for now I have merged the code without the git version part and retained the 0.8.1 version (as a start point).

**Pull request merged**
